# Generated by Django 6.0.5 on 2026-05-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='editorial/')),
                ('position', models.CharField(choices=[('manifesto', 'Brand Manifesto'), ('lookbook', 'Lookbook Strip'), ('edit', 'The VORN Edit'), ('usp', 'USP Strip')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('eyebrow', models.CharField(blank=True, help_text='Small caps label above title', max_length=100)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=10)),
                ('video', models.FileField(blank=True, null=True, upload_to='banners/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('cta_text', models.CharField(blank=True, default='Explore Collection', max_length=80)),
                ('cta_url', models.CharField(blank=True, default='/shop/', max_length=200)),
                ('cta2_text', models.CharField(blank=True, max_length=80)),
                ('cta2_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LookbookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('season', models.CharField(blank=True, help_text='e.g. SS26, AW26', max_length=50)),
                ('cover_image', models.ImageField(upload_to='lookbooks/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(default='gold', help_text='CSS color name or hex', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g. 30cm x 20cm x 5cm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.TextField(blank=True, help_text='Shipping & returns info shown on PDP'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Product weight in grams', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo review', null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.producttag'),
        ),
    ]
