databases:
  - name: vorn-postgres
    databaseName: vorn_db
    user: vorn_user
    plan: free

services:
  - type: web
    name: vorn-fashion
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn vorn_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-file - --access-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,vorn-fashion.onrender.com,.onrender.com"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: vorn-fashion.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://vorn-fashion.onrender.com,https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: vorn-postgres
          property: connectionString
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: RAZORPAY_KEY_ID
        value: "rzp_test_Su69JbzqTp4aKh"
      - key: RAZORPAY_KEY_SECRET
        value: "m4mb5wB0mb30Pk5R8I3JbGzr"
      - key: RAZORPAY_ME_LINK
        value: "https://razorpay.me/@vorn"
      - key: GROQ_API_KEY
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"

